# Module 1: Data validation and pre-processing technique

In [1]:
#import library packages
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
#Load given dataset
data = pd.read_csv("data.csv")

Before drop the given dataset:

In [4]:
data.head()

SFH  popUpWidnow  SSLfinal_State  Request_URL  URL_of_Anchor  web_traffic  \
0    1           -1               1           -1             -1            1   
1   -1           -1              -1           -1             -1            0   
2    1           -1               0            0             -1            0   
3    1            0               1           -1             -1            0   
4   -1           -1               1           -1              0            0   

   URL_Length  age_of_domain  having_IP_Address  Result  
0           1              1                  0       0  
1           1              1                  1       1  
2          -1              1                  0       1  
3           1              1                  0       0  
4          -1              1                  0       1

In [5]:
#shape
data.shape

(1353, 10)

After drop the given dataset:

In [6]:
df = data.dropna()

In [7]:
df.head()

SFH  popUpWidnow  SSLfinal_State  Request_URL  URL_of_Anchor  web_traffic  \
0    1           -1               1           -1             -1            1   
1   -1           -1              -1           -1             -1            0   
2    1           -1               0            0             -1            0   
3    1            0               1           -1             -1            0   
4   -1           -1               1           -1              0            0   

   URL_Length  age_of_domain  having_IP_Address  Result  
0           1              1                  0       0  
1           1              1                  1       1  
2          -1              1                  0       1  
3           1              1                  0       0  
4          -1              1                  0       1

In [8]:
#shape
df.shape

(1353, 10)

In [9]:
#columns
df.columns

Index(['SFH', 'popUpWidnow', 'SSLfinal_State', 'Request_URL', 'URL_of_Anchor',
       'web_traffic', 'URL_Length', 'age_of_domain', 'having_IP_Address',
       'Result'],
      dtype='object')

In [10]:
#To describe the dataframe
df.describe()

SFH  popUpWidnow  SSLfinal_State  Request_URL  URL_of_Anchor  \
count  1353.000000  1353.000000     1353.000000  1353.000000    1353.000000   
mean      0.237990    -0.258684        0.327421    -0.223208      -0.025129   
std       0.916389     0.679072        0.822193     0.799682       0.936262   
min      -1.000000    -1.000000       -1.000000    -1.000000      -1.000000   
25%      -1.000000    -1.000000        0.000000    -1.000000      -1.000000   
50%       1.000000     0.000000        1.000000     0.000000       0.000000   
75%       1.000000     0.000000        1.000000     0.000000       1.000000   
max       1.000000     1.000000        1.000000     1.000000       1.000000   

       web_traffic   URL_Length  age_of_domain  having_IP_Address       Result  
count  1353.000000  1353.000000    1353.000000        1353.000000  1353.000000  
mean      0.000000    -0.053215       0.219512           0.114560    -0.113821  
std       0.806776     0.762552       0.975970           0.318608     0.954773  
min      -1.000000    -1.000000      -1.000000           0.000000    -1.000000  
25%      -1.000000    -1.000000      -1.000000           0.000000    -1.000000  
50%       0.000000     0.000000       1.000000           0.000000    -1.000000  
75%       1.000000     1.000000       1.000000           0.000000     1.000000  
max       1.000000     1.000000       1.000000           1.000000     1.000000

In [11]:
#Checking datatype and information about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1353 entries, 0 to 1352
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SFH                1353 non-null   int64
 1   popUpWidnow        1353 non-null   int64
 2   SSLfinal_State     1353 non-null   int64
 3   Request_URL        1353 non-null   int64
 4   URL_of_Anchor      1353 non-null   int64
 5   web_traffic        1353 non-null   int64
 6   URL_Length         1353 non-null   int64
 7   age_of_domain      1353 non-null   int64
 8   having_IP_Address  1353 non-null   int64
 9   Result             1353 non-null   int64
dtypes: int64(10)
memory usage: 116.3 KB


Checking duplicate values of dataframe

In [12]:
#Checking for duplicate data
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1348     True
1349     True
1350     True
1351    False
1352     True
Length: 1353, dtype: bool

In [13]:
sum(df.duplicated())

629

In [14]:
#Checking sum of missing values
df.isnull().sum()

SFH                  0
popUpWidnow          0
SSLfinal_State       0
Request_URL          0
URL_of_Anchor        0
web_traffic          0
URL_Length           0
age_of_domain        0
having_IP_Address    0
Result               0
dtype: int64

In [15]:
df.SFH.unique()

array([ 1, -1,  0], dtype=int64)

In [16]:
df.popUpWidnow.unique()

array([-1,  0,  1], dtype=int64)

In [17]:
df.SSLfinal_State.unique()

array([ 1, -1,  0], dtype=int64)

In [18]:
df.Request_URL.unique()

array([-1,  0,  1], dtype=int64)

In [19]:
df.URL_of_Anchor.unique()

array([-1,  0,  1], dtype=int64)

In [20]:
df.web_traffic.unique()

array([ 1,  0, -1], dtype=int64)

In [21]:
df.URL_Length.unique()

array([ 1, -1,  0], dtype=int64)

In [22]:
df.having_IP_Address.unique()

array([0, 1], dtype=int64)

In [23]:
df.Result.unique()

array([ 0,  1, -1], dtype=int64)

In [24]:
df["Result"].value_counts()

-1    702
 1    548
 0    103
Name: Result, dtype: int64

In [25]:
df.corr()

SFH  popUpWidnow  SSLfinal_State  Request_URL  \
SFH                1.000000     0.375943        0.368690     0.257247   
popUpWidnow        0.375943     1.000000        0.218050     0.111520   
SSLfinal_State     0.368690     0.218050        1.000000     0.057239   
Request_URL        0.257247     0.111520        0.057239     1.000000   
URL_of_Anchor      0.333703     0.167760        0.088525     0.337277   
web_traffic       -0.187082    -0.140407       -0.171719    -0.045858   
URL_Length         0.151503     0.136229        0.095055     0.048431   
age_of_domain      0.163182     0.076815        0.208091     0.053348   
having_IP_Address  0.043349     0.123399        0.108000     0.013346   
Result            -0.678277    -0.509749       -0.518762    -0.271609   

                   URL_of_Anchor  web_traffic  URL_Length  age_of_domain  \
SFH                     0.333703    -0.187082    0.151503       0.163182   
popUpWidnow             0.167760    -0.140407    0.136229       0.076815   
SSLfinal_State          0.088525    -0.171719    0.095055       0.208091   
Request_URL             0.337277    -0.045858    0.048431       0.053348   
URL_of_Anchor           1.000000    -0.092045    0.097581       0.069178   
web_traffic            -0.092045     1.000000   -0.108204      -0.683857   
URL_Length              0.097581    -0.108204    1.000000       0.075338   
age_of_domain           0.069178    -0.683857    0.075338       1.000000   
having_IP_Address       0.039412    -0.094957    0.165152       0.040379   
Result                 -0.287007     0.243896   -0.183061      -0.231931   

                   having_IP_Address    Result  
SFH                         0.043349 -0.678277  
popUpWidnow                 0.123399 -0.509749  
SSLfinal_State              0.108000 -0.518762  
Request_URL                 0.013346 -0.271609  
URL_of_Anchor               0.039412 -0.287007  
web_traffic                -0.094957  0.243896  
URL_Length                  0.165152 -0.183061  
age_of_domain               0.040379 -0.231931  
having_IP_Address           1.000000 -0.059225  
Result                     -0.059225  1.000000

In [26]:
from sklearn.preprocessing import LabelEncoder
var=['SFH', 'popUpWidnow', 'SSLfinal_State', 'Request_URL', 'URL_of_Anchor',
       'web_traffic', 'URL_Length', 'age_of_domain', 'having_IP_Address',
       'Result']
le=LabelEncoder()
for i in var:
    df[i]=le.fit_transform(df[i]).astype(int)

In [27]:
df.head()

SFH  popUpWidnow  SSLfinal_State  Request_URL  URL_of_Anchor  web_traffic  \
0    2            0               2            0              0            2   
1    0            0               0            0              0            1   
2    2            0               1            1              0            1   
3    2            1               2            0              0            1   
4    0            0               2            0              1            1   

   URL_Length  age_of_domain  having_IP_Address  Result  
0           2              1                  0       1  
1           2              1                  1       2  
2           0              1                  0       2  
3           2              1                  0       1  
4           0              1                  0       2